name: Test site for fSquared Marketing
favicon: null
layout_spectrum: 0.3376411672215909
typography_spectrum: 0.5562555519863963
title: fSquared Marketing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.33885684655979276
  lightness: 0.9963897245470434
  saturation: 0.013220642693340778
  rhythmicContrast: 0.7392794508486986
purpose: []
